name: Build OS
on: [push]

jobs:
  build-kiddoz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Tooling
        run: sudo apt-get install -y g++ xorriso grub-pc-bin mtools libisoburn-dev

      - name: Compile and Package KiddozOS
        run: |
          # 1. Compile and Link
          g++ -m32 -ffreestanding -fno-exceptions -fno-rtti -c kernel.cpp -o kernel.o
          ld -m elf_i386 -T linker.ld kernel.o -o kernel.bin
          
          # 2. Setup ISO Folder Structure
          mkdir -p iso/boot/grub
          cp kernel.bin iso/boot/
          
          # 3. Create GRUB Config
          echo 'set timeout=0' > iso/boot/grub/grub.cfg
          echo 'set default=0' >> iso/boot/grub/grub.cfg
          echo 'menuentry "KiddoZ OS" {' >> iso/boot/grub/grub.cfg
          echo '  multiboot /boot/kernel.bin' >> iso/boot/grub/grub.cfg
          echo '  boot' >> iso/boot/grub/grub.cfg
          echo '}' >> iso/boot/grub/grub.cfg
          
          # 4. Generate the ISO
          grub-mkrescue -o kiddoz.iso iso
          
          # 5. Check if it actually exists (This will show in your logs!)
          ls -lh kiddoz.iso

      - name: Upload KiddoZ ISO file
        uses: actions/upload-artifact@v4
        with:
          name: KiddoZ-OS-Package
          path: kiddoz.iso  
          if-no-files-found: error 
