name: Kiddoz Bot
on:
  workflow_run:
    workflows: ["Build OS"]
    types:
      - completed

jobs:
  commit-iso:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: KiddoZ-Pi-Kernel
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Create and Commit ISO
        run: |
          git config --global user.name "KiddoZ-Bot"
          git config --global user.email "kiddoz.xperiments@gmail.com"
          rm -f kiddoz.iso
          cp kernel7.img kiddoz.iso
          git add -f kiddoz.iso
          git commit -m "Added KiddozOS V${{ github.run_number }}!"
          git push